#!perl
use 5.008001;
use strict;
use warnings;
use App::UpdateCPANfile;

my ($command) = shift @ARGV;

if ($command eq 'pin') {
    my $app = App::UpdateCPANfile->new(@ARGV);
    $app->pin_dependencies;
    exit 0;
} else {
    warn 'Usage';
    warn 'Pin Dependencies: update-cpanfile pin $PATH_TO_CPANFILE $PATH_TO_CPANFILE_SNAPSHOT';
    exit 1;
}

__END__

=encoding utf-8

=head1 NAME

update-cpanfile - cpanfile updater

=head1 SYNOPSIS

    $ update-cpanfile pin $PATH_TO_CPANFILE $PATH_TO_CPANFILE_SNAPSHOT

Pin package versions in cpanfile to versions in cpanfile.snapshot.

    $ update-cpanfile update $PATH_TO_CPANFILE

Not implemented yet.